# Generated by Django 4.1.4 on 2022-12-20 22:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
            ],
        ),
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=200, unique=True)),
                ('template_key', models.IntegerField()),
                ('body_style', models.CharField(default='circle', max_length=50)),
                ('eye_style', models.CharField(default='frame6', max_length=50)),
                ('eye_ball_style', models.CharField(default='ball6', max_length=50)),
                ('body_color', models.CharField(default='', max_length=50)),
                ('bg_color', models.CharField(default='', max_length=50)),
                ('eye_1_color', models.CharField(default='', max_length=50)),
                ('eye_ball_1_color', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
