# Generated by Django 4.1.4 on 2022-12-20 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_urls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyphonenumbers',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_phone', to='custom_urls.urls'),
        ),
        migrations.AddField(
            model_name='emergencyname',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_name', to='custom_urls.urls'),
        ),
        migrations.AddField(
            model_name='emergencyaddress',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_address', to='custom_urls.urls'),
        ),
    ]
