# Generated by Django 4.1.4 on 2023-01-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_urls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyqr',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyphonenumbers',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_phone', to='custom_urls.emergencyqr'),
        ),
        migrations.AddField(
            model_name='emergencyname',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_name', to='custom_urls.emergencyqr'),
        ),
        migrations.AddField(
            model_name='emergencyaddress',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_address', to='custom_urls.emergencyqr'),
        ),
    ]
