# Generated by Django 4.1.4 on 2022-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='bg_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='body_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='eye_1_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='eye_ball_1_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
