# Generated by Django 4.1.4 on 2022-12-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_urls', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_name', to='custom_urls.urls')),
            ],
        ),
    ]
